version: '3.8'

services:
  backend:
    container_name: smarter-backend-container
    build:
      context: .
    image: smarter-backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
