- name: Définir les configs Git pour {{ user.name }}
  become: true
  become_user: "{{ user.name }}"
  vars:
    git_config_entries:
      - { key: user.name, value: "{{ user.git.name }}" }
      - { key: user.email, value: "{{ user.git.email }}" }
      - { key: credential.helper, value: "store" }
  loop: "{{ git_config_entries }}"
  loop_control:
    loop_var: config
  git_config:
    name: "{{ config.key }}"
    value: "{{ config.value }}"
    scope: global

- name: Écrire le token GitHub dans .git-credentials
  become: true
  become_user: "{{ user.name }}"
  copy:
    dest: "/home/{{ user.name }}/.git-credentials"
    content: "https://{{ user.github_user }}:{{ user.github_token }}@github.com\n"
    mode: '0600'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  no_log: true
