- name: Configurer Git pour chaque utilisateur
  include_tasks: configurer_git.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  no_log: true

- name: Cloner le dépôt GitHub pour chaque utilisateur
  become: true
  become_user: "{{ item.name }}"
  git:
    repo: "{{ repo }}"
    dest: "/home/{{ item.name }}/Projects/erudi"
    version: main
    accept_hostkey: true
  loop: "{{ users }}"
  no_log: true

