"""baseline schema

Revision ID: 5ac171e299c6
Revises: 
Create Date: 2026-06-21 00:21:59.455743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac171e299c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_type', sa.String(), nullable=False),
    sa.Column('cpu_model', sa.String(), nullable=False),
    sa.Column('total_memory_gb', sa.Float(), nullable=False),
    sa.Column('available_memory_gb', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_available_gb', sa.Float(), nullable=False),
    sa.Column('global_inference_score', sa.Float(), nullable=False),
    sa.Column('global_inference_label', sa.String(), nullable=False),
    sa.Column('global_finetuning_score', sa.Float(), nullable=False),
    sa.Column('global_finetuning_label', sa.String(), nullable=False),
    sa.Column('cpu_score', sa.Float(), nullable=False),
    sa.Column('memory_score', sa.Float(), nullable=False),
    sa.Column('system_platform', sa.String(), nullable=True),
    sa.Column('gpu_name', sa.String(), nullable=True),
    sa.Column('estimated_tflops', sa.Float(), nullable=True),
    sa.Column('memory_bandwidth_gbs', sa.Float(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('gpu_score', sa.Float(), nullable=True),
    sa.Column('mlx_chip_model', sa.String(), nullable=True),
    sa.Column('mlx_gpu_cores', sa.Integer(), nullable=True),
    sa.Column('mps_available', sa.Boolean(), nullable=True),
    sa.Column('neural_engine_tops', sa.Float(), nullable=True),
    sa.Column('unified_memory', sa.Boolean(), nullable=True),
    sa.Column('cuda_cores', sa.Integer(), nullable=True),
    sa.Column('cuda_version', sa.String(), nullable=True),
    sa.Column('compute_capability', sa.String(), nullable=True),
    sa.Column('vram_total_gb', sa.Float(), nullable=True),
    sa.Column('vram_available_gb', sa.Float(), nullable=True),
    sa.Column('cpu_performance_units', sa.Float(), nullable=True),
    sa.Column('performance_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("backend_type IN ('mlx', 'cuda', 'cpu')", name='valid_backend_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_profiles_id'), 'hardware_profiles', ['id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('startup_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('welcome_popup_has_already_displayed', sa.Boolean(), nullable=False),
    sa.Column('models_seeded', sa.Boolean(), nullable=False),
    sa.Column('last_seeded_at', sa.DateTime(), nullable=True),
    sa.Column('offline_mode', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_variables_id'), 'startup_variables', ['id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'content_hash_sha256', name='uq_knowledge_documents_kb_hash')
    )
    op.create_index(op.f('ix_knowledge_documents_id'), 'knowledge_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_kb_id'), 'knowledge_documents', ['kb_id'], unique=False)
    op.create_table('llms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_metadata', sa.String(), nullable=True),
    sa.Column('quantized', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=True),
    sa.Column('param_size', sa.Float(), nullable=False),
    sa.Column('is_attached_to_kb', sa.Boolean(), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llms_id'), 'llms', ['id'], unique=False)
    op.create_index(op.f('ix_llms_name'), 'llms', ['name'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['llm_id'], ['llms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=False)
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_model_id', sa.String(), nullable=False),
    sa.Column('local_model_id', sa.Integer(), nullable=True),
    sa.Column('remote_model_link', sa.String(), nullable=False),
    sa.Column('temp_local_model_link', sa.String(), nullable=True),
    sa.Column('final_local_model_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_bytes', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('total_time_elapsed', sa.Float(), nullable=False),
    sa.Column('time_left', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['local_model_id'], ['llms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_id'), 'download_jobs', ['id'], unique=False)
    op.create_table('kb_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_model_id', sa.Integer(), nullable=True),
    sa.Column('new_model_id', sa.Integer(), nullable=True),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_model_id'], ['llms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_model_id'], ['llms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_jobs_id'), 'kb_jobs', ['id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('time_elapsed', sa.Float(), nullable=True),
    sa.Column('time_left', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['llm_id'], ['llms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_id'), 'training_jobs', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_training_jobs_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_kb_jobs_id'), table_name='kb_jobs')
    op.drop_table('kb_jobs')
    op.drop_index(op.f('ix_download_jobs_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_llms_name'), table_name='llms')
    op.drop_index(op.f('ix_llms_id'), table_name='llms')
    op.drop_table('llms')
    op.drop_index(op.f('ix_knowledge_documents_kb_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_startup_variables_id'), table_name='startup_variables')
    op.drop_table('startup_variables')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_hardware_profiles_id'), table_name='hardware_profiles')
    op.drop_table('hardware_profiles')
    # ### end Alembic commands ###
