- name: Configuration complète de la VM
  hosts: vm
  gather_facts: false
  become: true
  pre_tasks:
    -  name: Attendre que la VM soit atteignable en SSH
       ansible.builtin.wait_for_connection:
        timeout: 300
  tasks:
    - ansible.builtin.include_role:
        name: users
    - ansible.builtin.include_role:
        name: packages
    - ansible.builtin.include_role:
        name: clone_repo
