"""
Secrets management for Erudi backend.

This module handles sensitive environment variables (tokens, API keys, etc.)
that should not be committed to version control. Secrets are injected at:
  - Build time (CI/CD): Generated by build scripts, embedded in binary
  - Runtime (dev): Loaded from environment variables or .env file

This file is intentionally empty (or minimal) in version control and is
automatically generated/populated by build scripts (CI or local).

DO NOT COMMIT real secrets here.

Usage:
    from src.config.secrets import HF_TOKEN
    # HF_TOKEN will be available if injected at build/runtime
"""

# Hugging Face API token for model access.
# Injected at build time or loaded from environment.
# Format: hf_<random_string>
HF_TOKEN: str = ""  # Set by build process or CI

# Other potential secrets (add as needed)
# OPENAI_API_KEY: str = ""
# ANTHROPIC_API_KEY: str = ""
# DATABASE_PASSWORD: str = ""
