- name: Créer les utilisateurs
  user:
    name: "{{ item.name }}"
    groups: "{{ 'sudo' if item.sudo else '' }}"
    shell: /bin/bash
    state: present
    create_home: yes
  loop: "{{ users }}"
  loop_control:
      label: "{{ item.name }}"

- name: Créer les dossiers .ssh
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
  loop_control:
      label: "{{ item.name }}"

- name: Importer les clés publiques
  copy:
    src: "authorized_keys/{{ item.pubkey }}"
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
  loop_control:
      label: "{{ item.name }}"

